Repository silverstripe/silverstripe-subsites, pull requests merged in 2018-08, with the labels that each got.

#383 Loosen test assertion on content type for application/json
  tests/php/SubsiteXHRControllerTest.php
Labels: affects/v4, change/patch

#382 allow using queryParam to disable filter
  src/Extensions/GroupSubsites.php
Labels: affects/v4

#381 allow disabling filter using queryParam
  src/Extensions/FileSubsites.php
Labels: affects/v4

#386 API Deprecate duplicateSubsiteRelations. Use "cascade_duplicates" config API instead.
  src/Extensions/SiteTreeSubsites.php
Labels: affects/v4, change/minor

#387 FIX Pages now correctly duplicate children across subsites
  src/Extensions/SiteTreeSubsites.php
  tests/php/SiteTreeSubsitesTest.php
Labels: affects/v4, change/patch

#388 FIX CMS permission checks for subsite are now handled in the state context
  src/Controller/SubsiteXHRController.php
  src/Extensions/GroupSubsites.php
  src/Extensions/LeftAndMainSubsites.php
  src/Extensions/SiteTreeSubsites.php
  src/Model/Subsite.php
  tests/php/LeftAndMainSubsitesTest.php
  tests/php/SiteTreeSubsitesTest.php
Labels: affects/v4, change/patch
