Repository silverstripe/silverstripe-subsites, pull requests merged in 2019-06, with the labels that each got.

#418 Ensure URL segment field type before using its API, and add docs around subsite and fluent domain compatibility
  docs/en/introduction.md
  src/Extensions/SiteTreeSubsites.php
  tests/php/SiteTreeSubsitesTest.php
Labels: affects/v4, change/patch, type/docs

#425 FIX Subsites virtual pages now allow you to re-save them when used in conjunction with silverstripe-fluent
  src/Pages/SubsitesVirtualPage.php
  tests/php/SubsitesVirtualPageTest.php
Labels: affects/v4, change/patch

#428 Detect domains correctly in Director sub-calls
  src/Middleware/InitStateMiddleware.php
  tests/php/InitStateMiddlewareTest.php
Labels: affects/v4, change/minor

#430 FIX LeftAndMainSubsites::canAccess() now accepts a Member argument and falls back to the session member
  src/Extensions/LeftAndMainSubsites.php
  tests/php/LeftAndMainSubsitesTest.php
Labels: affects/v4, change/patch
